### ISSUE TITLE
Prereleases not catching dependency problems

### ISSUE THREAD

**Issue by stonier** [ros-infrastructure/jenkins_scripts#12]
Alot of dependency bugs showing up in releases that are not getting caught in the pre-releases.

The issue is discussed in [this thread](https://code.ros.org/lurker/thread/20130215.210319.ed321c7c.en.html) on the ros-release mailing list.

Tully sums it up well:

_The issues is that when testing several packages together, it pulls in the union of their system dependencies, but when building the debs, they only get their own declared ones.  We should make the prerelease capture each of their dependencies_

**Comment by dirk-thomas** [comment]
Since a prerelease inherently builds multiple packages in a single workspace `catkin_make` as well as `catkin_make_install` (which process packages in topological order) can always hide missing dependencies. The only solution would be a build which does not process packages in a single dimension ordered list but in a graph-fashion with only the specific dependencies of the branch being available.

Since no such build tool exists this is out of scope for the buildfarm.
